### ISSUE TITLE
Migrate Django code from /home/ubuntu to /srv

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_cloud#1]
Migrate web_code from /home/ubuntu to /srv
Figure out what process started the django server

Do this so multiple users can access the Django server rather than just one (`ubuntu`) as it is now.

**Comment by cheelee** [comment]
What's currently providing the service at http://movement.openworm.org/admin? I'm not currently seeing any running process on our AWS instance.

**Comment by cheelee** [comment]
@MichaelCurrie I have taken the first step of setting up the proper shared permissions for local repositories on the AWS instance. The following steps were taken using advice from this page - http://serverfault.com/questions/26954/how-do-i-share-a-git-repository-with-multiple-users-on-a-machine

1. Created a group "devs" (groupadd devs)
2. Created new folder /srv/git-repos owned by root, group devs with necessary permissions. This will serve as the root for all local git repositories.
3. Added yourself and myself to the devs group.
4. Set up a small test repository (a script to create new local repositories!) named "local_git." It contains a single script new_repo.sh you can use to add the contents of any folder you own as new shared repositories accessible by anyone in the devs group. Try it out - "git clone /srv/git-repos/local_git"

As for Django, I'm reading up more on how to do it right. Djangogirls does not quite cover everything to my satisfaction, especially on the issues of security and use of databases between development and deployment versions. Am currently working my mind through - http://stackoverflow.com/questions/22841764/best-practice-for-django-project-working-directory-structure

**Comment by MichaelCurrie** [comment]
> What's currently providing the service at http://movement.openworm.org/admin? I'm not currently seeing any running process on our AWS instance.

On the OWtestDB machine, there should be a process owned by the `ubuntu` user running python.  Otherwise it's witchcraft...

**Comment by cheelee** [comment]
It's witchcraft! 

In any event, I'm now trying to figure out what are the best practices for dealing with shared Django development, testing, and deployment. I think the best approach is to just shove the code we have into the initial repo, and then learn from there given our combined lack of experience with it right now. Ideally I'd like to have a repo where I can clone onto my Mac and test against a local DB (sqlite3,) and any code committed will also correctly deploy when pulled by the deployment account.

**Comment by cheelee** [comment]
@MichaelCurrie 
Initial git repo for the Django code is now created after some initial problems with permissions.

Try - 
locally:  git clone /srv/git-repos/movement_site
remotely: <user>@<ip>:/srv/git-repos/movement_site

I can close this issue once you test that this works. And then we can see how we'd want to clean this up for development purposes.

**Comment by cheelee** [comment]
This issue can now be closed as the server will now take code from this github repository.
