### ISSUE TITLE
Use HTML5 File API to directly load WCON files in viewer

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_cloud#100]
Currently the file is uploaded to the server and then downloaded once again.

This round-trip is done to bypass the old restriction that browsers cannot access the local file system.  However, if the user explicitly chose a file through the file picker, the new HTML5 File API allows us to access this file directly:

https://stackoverflow.com/questions/14740927/using-html-5-file-api-to-load-a-json-file

**Comment by cheelee** [comment]
Fixed!
