### ISSUE TITLE
Commas within fields invalidate resulting .csv files

### ISSUE THREAD

**Issue by rgerkin** [openworm/movement_cloud#120]
The .csv file produces from "Get Features Means Data" (using the default of all of the data with no filtering) produces a .csv file which cannot be parsed in e.g. Pandas because some of the fields themselves contain commas.  Since comma is also the separator for the .csv file, this results in extra columns which make unambiguous machine parsing of the file difficult/impossible.  

In the results.csv file that was produced, there were ~10 cases of this, all in the first column (base_name).  
Possible solutions: 
1) Sanitize these fields by replacing commas with semicolons
or
2) Use tab-separated instead of comma-separated values.

**Comment by cheelee** [comment]
Hi. The latest version should fix this issue. Please re-open this issue and let me know if they still occur. Thanks!
