### ISSUE TITLE
Focus on "core" features

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_cloud#13]
> Here's the list of 'core' features with a brief description.
> 
> - Andre
> 
> 
> 
> length - the length of the worm's midline
> 
> area - the area of the worm
> 
> midbody_bend_mean_abs - the absolute value of the worm's midbody bend angle
> 
> max_amplitude - the maximum distance between the points on the worm body that are farthest from the line connecting the head and the tail
> 
> head_tip_speed_abs - the absolute value of the worm's head speed (will capture some contribution from the high frequency 'foraging' motion of the worm's head).
> 
> midbody_speed_abs - the absolute value of the worm's midbody speed
> 
> path_range - the farthest distance recorded between the worm's staring point and any point on its trajectory during the recording
> 
> forward_motion_frequency - the frequency of forward motion bouts
> 
> paused_motion_frequency - the frequency of pauses (where the worm doesn't move much)
> 
> backward_motion_frequency - the frequency of reversals (where the worm moves backward for some time)

**Comment by cheelee** [comment]
I'm thinking of making these into a mirrored truncated list that sits above the full list of parameter features. They can be selected and deselected like the main list, and their effects will be mirrored on the main list.

**Comment by cheelee** [comment]
The implementation of the core features list as discussed have been completed and checked into the master branch. In a little git discipline boo-boo, I will also have to check in the exact copy in the dev branch.
