### ISSUE TITLE
Features Means: Foreign Key link with Experiments

### ISSUE THREAD

**Issue by cheelee** [openworm/movement_cloud#14]
FeaturesMeans isn't currently linked with Experiments, and what I assumed to be the foreign key in FeaturesMeans (experiment_id) is of a different size (Big20) from the id maintained with Experiments.

**Comment by cheelee** [comment]
@ver228 Hi Avelino. It looks like the new database still does not have the features_means table linked to experiments table via a foreign key. Will need that set up in order to get Django to smoothly filter queries on features.

**Comment by ver228** [comment]
That's a weird. It should be there already. If you use  `SHOW CREATE TABLE features_means;` there is the line:
```
CONSTRAINT `features_means_ibfk_1` FOREIGN KEY (`experiment_id`) REFERENCES `experiments` (`id`)
```

I know it works because I have been using it to retrieve features locally as:
```
SELECT base_name, strain, strain_description, f.*
FROM experiments_full
RIGHT JOIN features_means AS f ON experiment_id=id
```

**Comment by cheelee** [comment]
@ver228 Ignore my last comment - it looks like the Foreign Key is present. I was just looking for it in the wrong place (the Experiments table instead of the Features Means table where it is found)
