### ISSUE TITLE
Generate Test Database CSV

### ISSUE THREAD

**Issue by cheelee** [openworm/movement_cloud#2]
@MichaelCurrie Is it possible to dump a CSV file from the database instead of a .sql file? I'm encountering significant difficulty trying to import the latter into an sqlite3 database we could use as a convenient test database for development purposes.

**Comment by MichaelCurrie** [comment]
Sure, sounds good.  I believe something alone these lines should do it:

https://stackoverflow.com/questions/4613465/using-python-to-write-mysql-query-to-csv-need-to-show-field-names

**Comment by cheelee** [comment]
This issue can now be considered deprecated and closed. There are far more convenient ways to update and archive the databases used by this project.
