### ISSUE TITLE
Add JSON processing to server environment

### ISSUE THREAD

**Issue by cheelee** [openworm/movement_cloud#20]
I have added features that require JSON file processing. requirements.txt reflects this.

For now, we will need to add "pip install simplejson" to the static server software stack environment.

In the future we should consider a setup framework that allows us to automatically take server systems that satisfy basic requirements, and then augment them to satisfy any additional software stack requirement changes due to changes in the repo. The clearest example of this is if we need support for more python modules like matplotlib.

**Comment by MichaelCurrie** [comment]
OK I executed the command `sudo pip3 install simplejson` on the dev server.  Please let me know if we need anything else.

I agree that having `requirements.txt` is perfect for accumulating these things.  I also like having a makefile script that goes from clean ubuntu AWS instance to configured server.  But perhaps `requirements.txt` will work just as well for this small amount of server configuration needed.
