### ISSUE TITLE
Sex search leads to "Service unavailable" 

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_cloud#31]
If I do a search and select all Males but do not narrow the search in any other way, and click the red search button, I get a page that simply says "Service unavailable" in plain text in the upper left corner.

**Comment by cheelee** [comment]
I just did a brief probe ... somehow selecting "male" ends up producing all results. Will investigate further.

**Comment by cheelee** [comment]
Ok this is a bizarre bug. I will need more time to look into this ... for some reason only for the sex field, the operation inside the function succeeds but fails to propagate the results outside the function. 

Note that this is a parameterized function - every field shares exactly the same code. The input is correct, it triggers the correct Django database filter, and produces the expected number of entries in the resulting queryset. Yet this queryset does not get correctly returned ...

**Comment by cheelee** [comment]
I am temporarily removing this discrete field from consideration in the filtering process.

**Comment by MichaelCurrie** [comment]
Let's make this a "wontfix" then.

**Comment by cheelee** [comment]
Yah, but should probably keep an eye out in case that discrete field is desired as a filter option. There's something really weird about it.
