### ISSUE TITLE
Limit the number of search results

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_cloud#34]
As a sanity check, to avoid the server returning thousands of results, perhaps there should be a limit of 50 in the search results page.

This would fix the problem of thousands of youtube videos on one page...

The url download file generated can contain the full list, though.

**Comment by cheelee** [comment]
If I am not wrong, the paging capabilities of DataTables handles that, rendering only the first page. I can check if it is still a performance problem in spite of DataTables' pagination rendering optimizations.

**Comment by MichaelCurrie** [comment]
I thought all those YouTube videos being rendered were killing your computer?

**Comment by cheelee** [comment]
That's on error conditions. For example when the HTML generated cannot be properly processed by DataTables, and 14k records are simultaneously loaded. Under normal circumstances, it is quite reasonable.

**Comment by MichaelCurrie** [comment]
You don't sound concerned :)  I misunderstood.  So I will close this issue :)

**Comment by cheelee** [comment]
Cool, I think we can close the issue for now. It is something to be concerned about if whatever is processing video links fails, or fails to be paged with regard to rendering. So if such a performance issue crops up, we can reopen this issue.
