### ISSUE TITLE
Start on the "Search Tools" tab

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_cloud#35]
Rather than starting on the Results tab, if there are no results yet, start on the "Search Tools" tab instead.  This will be more intuitive for users.

![image](https://cloud.githubusercontent.com/assets/5267078/25946122/f4076084-3673-11e7-9c85-ea373962a47c.png)

**Comment by cheelee** [comment]
Done, but the results are not optimal. Django will complete a search and put the user back in the search tab. There are two ways we can make this less jarring - 

1. highlight the Results tab whenever there is new information available
2. use jQuery to trigger the active tab to Results whenever new results populate the Results tab.

Keeping this issue open until reasonably resolved.

**Comment by cheelee** [comment]
Chose to trigger the active tab to Results when there are Results to show. It feels fine to me now. Closing the issue.
