### ISSUE TITLE
Add WCON viewing page with visualization of worm

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_cloud#48]
Progress:

- incorporate sperm animation (https://bl.ocks.org/mbostock/1136236) into chart  DONE
- add border to sperm animation DONE
- figure out how to control # of results DOM element.    DONE
- vary the number of sperm shown based on how many results are returned    DONE
- hide worms, don't just kill them: http://bl.ocks.org/d3noob/5d621a60e2d1d02086bf  MOOT
- make sperm look like worms  (using https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths, e.g. https://codepen.io/Klaujesi/pen/Meajyx)  DONE
- add tooltip like in https://github.com/MichaelCurrie/bubble_chart  MOOT
- move the results window to the right  MOOT
- link to real worm data (may still depend on simplifying the representation as in https://github.com/openworm/tracker-commons/issues/133, or maybe not, if we just export a 5-second clip of each WCON file)   DONE

CSS selectors:

.class
#id
*
element   e.g.   p    selects all <p> elements

**Comment by MichaelCurrie** [comment]
Current bottleneck: the visualization works locally but when I try running it on AWS I get this error:

![image](https://cloud.githubusercontent.com/assets/5267078/26034627/b84b307a-38e9-11e7-98e7-982aa5f92821.png)

I'm stil hoping it's just a browser cacheing issue.

**Comment by MichaelCurrie** [comment]
It was a browser cacheing issue.

**Comment by MichaelCurrie** [comment]
To link to real worm data, I wrote this truncation script to shrink the size of a given wcon file to just the first 10 seconds:

```python
# -*- coding: utf-8 -*-
import sys

sys.path.append('..')
from wcon import WCONWorms

import tests

tests.setUpModule()

file_name = 'asic-1 (ok415) on food L_2010_07_08__11_46_40___7___5.wcon'
w = WCONWorms.load_from_file(file_name)

# Truncate to just the first 10 seconds
w.data_as_odict['1'] = w.data_as_odict['1'].ix[0:10]

# Grab the first 10 frames (doesn't work since the first 3885 frames are NaN)
#w.data_as_odict['1'] = w.data_as_odict['1'].iloc[:10]

# View the experiment data as a CSV (so it can be loaded in Excel, for instance)
#w.data_as_odict['1'].to_csv('bbb.csv')

# Save the smaller file
w.save_to_file('smaller.wcon')

tests.tearDownModule()
```

**Comment by MichaelCurrie** [comment]
Working on path simplification for the worm visualization:
https://bost.ocks.org/mike/simplify/
https://bl.ocks.org/mbostock/5732029

**Comment by MichaelCurrie** [comment]
It's better to have this worm visualization on a separate tab, as it is too gimmicky on the search results page.  The worm visualization can be a part of a page for WCON file viewing.

**Comment by MichaelCurrie** [comment]
Here's a mockup of what that separate tab might look like.  We could use www.dropzonejs.com for the drag-and-drop uploading screen.

I will try to do something fast before implementing the fancy features, just to get feedback first.

![image](https://cloud.githubusercontent.com/assets/5267078/26527215/011c5a4c-434c-11e7-8a34-7f557ee2ba1b.png)

**Comment by MichaelCurrie** [comment]
I've got a hello world page up now, in /WCON_viewer/:

![image](https://cloud.githubusercontent.com/assets/5267078/26527366/d0481d44-434f-11e7-98c9-04efe11352ea.png)

Working on adding to it.

**Comment by MichaelCurrie** [comment]
I've now got it showing the units and metadata, but I wonder if I could attractively present them (at least the units) in a tabular format instead.

![image](https://cloud.githubusercontent.com/assets/5267078/26527573/bd258f4a-4353-11e7-9635-06083d4bcd27.png)

**Comment by MichaelCurrie** [comment]
@ver228 I've found two validation errors in the test WCON file:

- the "timestamp" format used needs to include the time zone as per https://tools.ietf.org/html/rfc3339
- the frame rate has not been specified.  units.t = "s" but it should be "0.04s" for 25fps, for instance.

**Comment by MichaelCurrie** [comment]
With a51d7c4 all that is left to do for the MVP version of this is some facility to upload a WCON file.  Right now it is just showing the results from a static file sitting in the folder.

Also, making it look prettier by adding spacing between the elements. and perhaps labeling the animation with frames (or time steps).

![image](https://cloud.githubusercontent.com/assets/5267078/26563376/8f94bd94-448e-11e7-8f2f-81ebb4dd80f8.png)

**Comment by MichaelCurrie** [comment]
Maybe I should add a graph showing distance from start over time so the time axis can be shown visually.  Then as the animation moves a point on that chart can be highlighted.

**Comment by MichaelCurrie** [comment]
Also show min and max timestep and fps in the t dimension.

**Comment by MichaelCurrie** [comment]
I verified the viewer works after about 3 seconds with a 58 megabyte real WCON file, rather than the toy example I was working with.  Good!

![image](https://cloud.githubusercontent.com/assets/5267078/26618082/f44fb38a-4595-11e7-9619-bb0908cc8ba4.png)

**Comment by MichaelCurrie** [comment]
Add progress bar for the download, after the upload :)

https://kimmobrunfeldt.github.io/progressbar.js/

**Comment by MichaelCurrie** [comment]
Multiple worm capability via dropdown and multiple visualization.  @Ichoran let me know which you think is better: for the dozens of worms in your test file, I could create a table showing small visualizations for all of them, or you could reach them by a drop down.  Here I am showing a table of two visualizations, plus the drop down box at the bottom letting you pick which worm is shown in the first chart.

![image](https://cloud.githubusercontent.com/assets/5267078/26773803/1ffb26de-498a-11e7-93a3-044a150d5a8e.png)

**Comment by Ichoran** [comment]
@MichaelCurrie - I'd probably go for a worm at a time, or maybe a higher-temporal-resolution worm at a time that you've picked, with a low-temporal-resolution pale background of all the tracks (e.g. low-res pale blue of everything you haven't selected).  But whatever is easiest is fine--what you have above is already great!

**Comment by MichaelCurrie** [comment]
OK, thanks.  By the way @Ichoran it looks like your worms are writing in the "Arrival" alphabet :)

![download](https://cloud.githubusercontent.com/assets/5267078/26790455/feceeed6-49d0-11e7-83cc-07fc2b3617e5.png)

![download](https://cloud.githubusercontent.com/assets/5267078/26790468/075cb574-49d1-11e7-9fbd-67ef39f03080.jpg)

**Comment by Ichoran** [comment]
They're writing out, "Hey, there's too much oxygen here!"

**Comment by MichaelCurrie** [comment]
@Ichoran wow https://berkeley.edu/news/media/releases/2004/07/07_worms.shtml did not realize they preferred 6% oxygen, and clumping is not social behaviour but low-oxygen-seeking behaviour.

**Comment by MichaelCurrie** [comment]
Remaining to-do items for this based on feedback from @aexbrown and @ver228:

- add controls to video
- drop the axes
- add scale bar instead
- toggle the track?
- grey track
- integrate feature calculation once worm has been uploaded, and also append to database
- use bootstrap CSS to make page look nicer
- Integrate WCON viewer into Django site
- handle wheel event after zooming out so it is a dead zone for scrolling https://github.com/d3/d3-zoom/blob/master/README.md#zoom_scaleExtent

**Comment by MichaelCurrie** [comment]
I've learned that timerFlush doesn't stop all timers, it just triggers all pending timer events.  I will still need to create callbacks so uploading a new file stops the old timer.

The best solution will be for the dropzone.js to programmatically "click" the PAUSE button if it hasn't already been clicked.

Then I can remove all that timerFlush() code.  (or maybe leave it!)

**Comment by MichaelCurrie** [comment]
`timerFlush` issue fixed now, by using a simulated event click from https://stackoverflow.com/questions/2705583/how-to-simulate-a-click-with-javascript:

`
function stop_animation() {
    function eventFire(el, etype){
      if (el.fireEvent) {
        el.fireEvent('on' + etype);
      } else {
        var evObj = document.createEvent('Events');
        evObj.initEvent(etype, true, false);
        el.dispatchEvent(evObj);
      }
    }
    let toggle_button = document.getElementById('toggle_animation_button');
    if(toggle_button.innerHTML === "PAUSE") {
        eventFire(toggle_button, 'click');
    }
}
`

**Comment by MichaelCurrie** [comment]
Remaining to finish:

- Integrate WCON viewer into Django site
- integrate feature calculation once worm has been uploaded, and also append to database
- use bootstrap CSS to make page look nicer: https://getbootstrap.com/examples/grid/ or https://v4-alpha.getbootstrap.com/examples/

**Comment by MichaelCurrie** [comment]
I'll declare 397b9b69e1b05c0a10caea8c9ce5fc5a713108f8 feature-complete and merge it into dev.

**Comment by MichaelCurrie** [comment]
Done with #91.
