### ISSUE TITLE
Why so many -0.04 entries?

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_cloud#49]
Hi Avelino,

I'm just looking at the two example worms you had sent to me:

![image](https://cloud.githubusercontent.com/assets/5267078/26057274/25687960-39a3-11e7-96c7-5370e8ea8426.png)

Now at the .wcon file: https://www.dropbox.com/s/rvy4vwhwoj4o7l8/asic-1%20%28ok415%29%20on%20food%20L_2010_07_08__11_46_40___7___5.wcon?dl=0

Seems to have 3885 entries for "t" at -0.04, before the time increments normally.  Is there a reason for this?

Thanks

**Comment by ver228** [comment]
@MichaelCurrie  Sorry, there was I bug. I updated the files. Could you take a look again?

**Comment by MichaelCurrie** [comment]
Thanks.

Is it easy for you to tell me that I can just ignore the -.04 entries, or is it necessary for me to re-download?

Thanks

**Comment by ver228** [comment]
You can ignore them, but if you can it might be better to download again the wcon files.

**Comment by MichaelCurrie** [comment]
OK thanks!
