### ISSUE TITLE
Row Selection: Possible bug with Chrome version 57.0.2987.133

### ISSUE THREAD

**Issue by cheelee** [openworm/movement_cloud#55]
This will need to be tested.

**Comment by cheelee** [comment]
Hmmm tried it with Chrome Version 58.0.3029.110 (64-bit) on Mac OS X and it works fine. Will investigate further with reports that it fails.

**Comment by MichaelCurrie** [comment]
It works for me on  58.0.3029.110

**Comment by MichaelCurrie** [comment]
It works for everyone except André on Chrome, but he's using an older version.  So we'll close this issue for now unless it appears again.
