### ISSUE TITLE
Documentation: Create Developer/Maintainer Documentation

### ISSUE THREAD

**Issue by cheelee** [openworm/movement_cloud#60]
Create a document to help guide people maintaining their own database, and running the Django server.

**Comment by MichaelCurrie** [comment]
e.g. we could have documentation for how to change the DB schema if tracker commons is changed:

on dev server:
tracker commons change metadata
on aws server add column
export schema with mysqldump
run migrations on movement_cloud django
commit migrations and schema
promote to production

on prod server
copy database?
pull from master

**Comment by MichaelCurrie** [comment]
Done.  https://github.com/openworm/movement_cloud/blob/dev/webworm_docs/README.md

We can add to this document as more processes come up.
