### ISSUE TITLE
WCON files need fixes to frame rate and timestamp

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_cloud#65]
@ver228 I found two problems with the sample WCON files you have given me:

- the "timestamp" format used needs to include the time zone as per https://tools.ietf.org/html/rfc3339
- the frame rate has not been specified.  units.t = "s" but it should be "0.04s" for 25fps, for instance.

**Comment by ver228** [comment]
I am a bit confused with the frame rate definition. Currently the time vector has units of `"s"` looks like `t: 0.04, 0.08, 0.12`. If I change the units to `"0.04s"` then I should change the time vector to `t: 1, 2, 3`. I can use any of them, but I would have expect that they are both accepted.

**Comment by ver228** [comment]
I am currently generating that string using a `datetime` object and using the method `isoformat`. I do not seem to find an easy way to define the timezone but using the an external library (pytz). Maybe you have a suggestion.

However, I am not sure I agree with the need to include the time zone.  Typically we would care more about the relative time of the day since the worms might follow circadian rhythms. I do not think we really care if a given experiment was done at the same moment in Singapore or in England.

**Comment by MichaelCurrie** [comment]
1. You're right, both frame rate approaches are acceptable.  That was my mistake.

2. As for the time zone, I was inclined to agree with you until I read what the IEEE standards document says about your idea to use local time (https://tools.ietf.org/html/rfc3339#section-4.4):  :)

> 4.4. Unqualified Local Time
>
> A number of devices currently connected to the Internet run their internal clocks in local time and are unaware of UTC.  While the Internet does have a tradition of accepting reality when creating specifications, this should not be done at the expense of interoperability.  Since interpretation of an unqualified local time zone will fail in approximately 23/24 of the globe, the interoperability problems of unqualified local time are deemed unacceptable for the Internet.  Systems that are configured with a local time, are unaware of the corresponding UTC offset, and depend on time synchronization with other Internet systems, MUST use a mechanism that ensures correct synchronization with UTC.

If someone has the use case you suggest of tracking circadian rhythms they always have the option of storing the local time with the offset rather than just storing UTC.  In fact, this would be the preferred representation since it would allow for both absolute time and time relative to circadian rhythms to be studied and used.

Furthermore since British Summer Time is used in Cambridge during the summer months, storing the time as a naive system clock time may introduce a discrepancy of one hour in the records.

So if you agree with me, currently you use: `2010-07-08T11:46:40`

Options:

`2010-07-08T11:46:40Z`   (append a `Z` to represent UTC)
`2010-07-08T11:46:40+00:00` during the winter months and
`2010-07-08T11:46:40+01:00` during the summer months.

I wrote a gist explaining how to use `pytz` to create timezone-aware timestamps: https://gist.github.com/MichaelCurrie/fa4096710ef6c6ae65b0

Here's how we could do the conversion:

```python
# -*- coding: utf-8 -*-
"""
Change the timezone naive timestamps to timezone-aware timestamps

"""
import datetime
import pytz

# Use this to load from an actual file:
# import json
# with open('example.wcon') as file_handle:
#     wcon_dict = json.load(file_handle)
    
# Instead of loading a file let's just use this faked example:
wcon_dict = {
        "metadata": {
            "timestamp": "2010-07-08T11:46:40",
        },
    }

# Assume the experiments took place in Cambridge, UK
local = pytz.timezone ('Europe/London')
naive = datetime.datetime.strptime(wcon_dict['metadata']['timestamp'],
                                   '%Y-%m-%dT%H:%M:%S')
# Cambridge, UK has BST (UTC+1) in the summer months, which we assume was
# already baked into the timestamp
local_dt = local.localize(naive, is_dst=True)

wcon_dict['metadata']['timestamp'] = local_dt.isoformat()

# Uncomment this line to save the changed file
# with open('example.wcon', 'w') as file_handle:
#         json.dump(wcon_dict, file_handle)

# Instead we'll just print the result to see
print(input_wcon)
```

**Comment by MichaelCurrie** [comment]
@ver228 introduced this fix via:

https://github.com/ver228/single-worm-analysis/commit/f0789feff2b9dfefb6f27edaa2b24913b4e8ed4d

@ver228 in the example file there was also a problem with "t" entries of "-0.04" appearing for several thousand rows.  Do you know if this has been fixed?  Thanks!

**Comment by ver228** [comment]
It should be fixed in the latest version of my WCON exporter.

**Comment by MichaelCurrie** [comment]
OK I'll close this issue now.  Thanks!
