### ISSUE TITLE
Extended Test Database

### ISSUE THREAD

**Issue by cheelee** [openworm/movement_cloud#7]
Create new extended test database with links to -

1. experiment data files (Zenodo archive)
2. youtube videos that demonstrate key worm movement characteristics. The goal is to embed the videos in the database interface users can view after filtering.

**Comment by cheelee** [comment]
The disparate pieces are in place.
1. We have some youtube videos up.
2. We have some Zenodo data up (on their sandbox server).
3. We have stub links to both pieces of data in the current Web Interface.
4. We DO NOT have the link information for either available yet in the actual database.
5. We DO NOT have actual links we can use in the Web interface.

**Comment by MichaelCurrie** [comment]
Hi @cheelee perhaps we could discuss exactly what's needed here.  Basically a separate table, like `experiment_links`, with columns:

`experiment_id` (foreign key to the `experiments` table)
zenodo link
youtube link
local machine link (file name)

Please let me know what you think.

**Comment by cheelee** [comment]
I think that is fine for now. We will probably need to do extensive restructuring of the database to enhance performance later.

**Comment by cheelee** [comment]
These two tables look to be in place in the new database. I'm closing the issue, and opening a new one for implementing code to draw data from those two tables in populating the interface output.
