### ISSUE TITLE
Crossfilter: Crossfiltered results lists are temperamental

### ISSUE THREAD

**Issue by cheelee** [openworm/movement_cloud#72]
Right now, simply having too many column elements (e.g. default landing page info has only 3 and it is already a problem) causes it to lose display information. The space allocated for each column looks pretty bad.

It is unclear if DataTables is too heavy-weight an implementation to support the fast redraw rates the current result list supports, but we can give it a try. DataTables takes care of a lot of layout issues, and generally comes across as polished when used.

**Comment by cheelee** [comment]
I have replaced the results list displays with a more flexible table-based implementation. Performance with a limited number of displayed rows (max 20) has not been impacted. Tables just need to be made prettier. This fixes this issue, a better solution is if DataTables can be applied.

**Comment by MichaelCurrie** [comment]
Hi @cheelee do you think the new table is better in some way than the old?

It looks more "basic" as you say, and also because the widths are not fixed by spans, the column widths jitter around when you play with the crossfilter filters.

![image](https://user-images.githubusercontent.com/5267078/27107767-ba487da2-504e-11e7-805e-fd4d97b4a6d7.png)

Is there a reason to eliminate the old way?  Thanks!

**Comment by cheelee** [comment]
The old chart had hardcoded CSS width specifications based on ID tags, with significant inflexibility where it came to layout. You will notice that the text will overlap because of the lack of control. Ultimately any extra code that can be written to make the old chart look good will almost certainly default to anything table implementations do in the first place, imho.

I have not noticed any jittering with the column widths ... they shouldn't, since their widths are determined by the headers ... hmmm I'll need to take a look.

**Comment by MichaelCurrie** [comment]
OK makes sense - if we can fix the jittering, then that's good for me!  Perhaps we can put a "width" parameter for each entry in `data_fields` in `crossfilter_parameters.js`.

**Comment by cheelee** [comment]
Not sure if that is possible for tables. The only way I can think of is for some way to scan ALL elements in the data for the longest string, and pre-determine the widest possible value to be rendered.

Personally the jitter is not as serious a problem as text that bleed into each other and becomes illegible.

**Comment by cheelee** [comment]
This has been successfully fixed using tables. Closing. Using DataTables for this table may be something to consider in another issue.
