### ISSUE TITLE
Download Button full implementation

### ISSUE THREAD

**Issue by cheelee** [openworm/movement_cloud#74]
Currently the Download button will produce a pseudo-record list for only the displayed results from the crossfilter process. It needs to be augmented to:

1. produce lists for all selected records from the crossfilter process.
2. produce lists of URLs (e.g. Zenodo) that can be useful for subsequent processing.

**Comment by cheelee** [comment]
@ver228 @MichaelCurrie - Are we ready to populate the database with zenodo links and the size of original data in MB? The current test database I am using has NULL values for all records in the Experiments table. Somehow I thought we already had this information available from before, but I don't see it. Any ideas?

**Comment by cheelee** [comment]
@ver228 @MichaelCurrie - Ok I just checked. The 250117 database had values for original data in MB (along with the local file paths to the video files), but in our latest test database the size field is NULL but the path names are still there.

**Comment by MichaelCurrie** [comment]
@cheelee I am working on writing the script for @ver228 to execute here: https://github.com/openworm/movement_cloud/issues/92

The field is not currently populated in `mrc_db4`; the following query returns 0 rows:

```
select * from experiments where zenodo_id is not null;
```

For now, I have populated that field with the example I manually uploaded to sandbox.zenodo: https://sandbox.zenodo.org/record/71862#.WUWGBWg1-M8

```
update experiments set zenodo_id = '71862#.WUWGBWg1-M8' where zenodo_id is null;
```

**Comment by cheelee** [comment]
@MichaelCurrie I have some slight concern about the possible fragility of using the experiment's full name in the name of the files for Zenodo. I am assuming that is how you have been uploading the data to Zenodo. I've seen some funky names used. For now I'm assuming they are all going to work, and deal with exceptions as they come along. The protocol I am using for determining what the useful URLs are from the base Zenodo link is:

Expansions = link (above) + “/files/<full name> + 
“.hdf5”
“.wcon.zip”
“_features.hdf5”
“_skeletons.hdf5”
“_subsample.avi”

**Comment by cheelee** [comment]
This functionality is now implemented and tested against dummy values, with the caveats on file names as indicated above.

**Comment by cheelee** [comment]
Without reopening the issue, I had fixed a misunderstanding I had over Zenodo Ids. The current code in the integrate_viewer branch handles Zenodo Ids correctly now. The server currently uses a single Zenodo Id for all entries in its test database, so people can click on "Download Experiments List" to get a list of semi-faked URLs. These ought to be correct in form, but will only really work on exactly one Experiment (since all the rest do not actually have corresponding Zenodo data entries.) @ver228 @MichaelCurrie - Feel free to give it a try. Live on the current server now.
