### ISSUE TITLE
Feature: Short pretty names, and unit information for each Feature

### ISSUE THREAD

**Issue by cheelee** [openworm/movement_cloud#78]
It would be great if we had good short names for each Feature if possible. So for example, "Midbody Bend Mean" instead of "midbody_bend_mean_abs."

More importantly, we should have units for each of the features, unless they are counts of some sort. This will involve a change to the features descriptions table in the database.

**Comment by MichaelCurrie** [comment]
Luckily this information is already available in table form:

https://github.com/openworm/open-worm-analysis-toolbox/blob/master/open_worm_analysis_toolbox/features/feature_metadata/features_list.csv

We should put this table in the database. (actually this could just be extra columns on "features")

**Comment by cheelee** [comment]
This isn't really a problem anymore when tables are used for crossfilter. Am closing the issue. It can be re-opened later if this becomes a problem again.
