### ISSUE TITLE
Database issue?  Strains missing records?

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_cloud#84]
André mentioned this when previewing the site last week.

Perhaps it's not but I saw this as well in crossfilter a while back.

![strains missing records](https://user-images.githubusercontent.com/5267078/26966079-de2d43c0-4cb5-11e7-92cd-f2fd2862b974.png)

**Comment by cheelee** [comment]
Clarifying question - what exactly is missing or wrong? I have done non-systematic sanity checks on those values before ... as far as I can tell, they check out vis-a-vis the database.

**Comment by MichaelCurrie** [comment]
What's missing are possibly the 2561 "allele" values for the strains here that are not "N2":

![image](https://user-images.githubusercontent.com/5267078/27161686-e88f9392-5131-11e7-9745-efeb3d6e47fa.png)

for instance:

814 JU393 on food R_2011_03_08__16_28___3___11

But I have no idea if this is a data gap or not.  Let's let @aexbrown raise this issue again if he sees something wrong.

**Comment by MichaelCurrie** [comment]
FYI I originally got worried when I saw results like this, where there were lots of N2 / N/A coming back:

![image](https://user-images.githubusercontent.com/5267078/27161798-95e44f10-5132-11e7-8310-24933b500321.png)

But upon further reflection N2 worms probably always have N/A as their allele, and perhaps there is a reasonable explanation for the non-N2 worms without an allele too.

**Comment by aexbrown** [comment]
That's right, JU393 is the strain name of a wild isolate.  It will have many different genetic differences as opposed to one known genetic difference that we would label with a 'gene(allele)'.
