### ISSUE TITLE
Integrate WCON viewer into Django site

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/movement_cloud#90]

**Comment by MichaelCurrie** [comment]
Working on this from https://github.com/openworm/movement_cloud/tree/integrate_viewer.

Some issues getting the javascript to work now that it's not in a standalone HTML page.

In particular setting DOM element properties etc at the time of the js script load does not work because the tab has not had its DOM activated yet.  @cheelee is there some kind of "on_pane_loaded" and "on_pane_exited" event that I should be listening for?  Then I think I might be able to fix it myself.  Thanks!

**Comment by cheelee** [comment]
The bug is fixed. Turned out the previous code did not properly install the WCON Viewer pane, and so none of the Javascript code could find the DOM elements.

@MichaelCurrie Give it a try, and you may close this issue if the feature is considered properly integrated to your satisfaction! :)

**Comment by MichaelCurrie** [comment]
Great, I think this is much closer!  But I tried it on the server and I get:

![image](https://user-images.githubusercontent.com/5267078/27271751-55387bca-547b-11e7-8d63-9c3b5090f47f.png)

So I think we just need to get `example.wcon` loaded somehow.

**Comment by cheelee** [comment]
Wait a minute ... that should work. I fixed that along with the other WCON bug. Are you on the right branch? https://github.com/openworm/movement_cloud/blob/integrate_viewer/webworm/static/webworm/wormviz_parameters.js should have the file path be wconFilePath, and index.html should construct that from Django's static template. Last I tested it, that was working.

I'll take a look at what the server sees.

**Comment by cheelee** [comment]
Ok I just tried it on the server and it is working. Are you sure you're not using some sort of cached copy? I'm leaving it running on the server so you can take a look hehe.

![screen shot 2017-06-19 at 3 53 17 pm](https://user-images.githubusercontent.com/316749/27274856-8deb5a3c-5507-11e7-837a-98e82fbf46b4.png)

**Comment by cheelee** [comment]
This feature is now in its own independent Django url page - http://movement.openworm.org/wconviewer

**Comment by cheelee** [comment]
I believe this can now be closed.
